import turtle
screen = turtle.Screen()
screen.bgcolor("white")
turtle.speed(2)

turtle.penup()
turtle.goto(40, -40)
turtle.color("#FA0A0A")
turtle.begin_fill()
turtle.setheading(0)
turtle.pendown()
turtle.forward(100)
turtle.left(120)
turtle.forward(50)
turtle.left(60)
turtle.forward(100)
turtle.goto(40, -40)
turtle.end_fill()

turtle.penup()
turtle.goto(-10, -90)
turtle.color("#43B02A")
turtle.begin_fill()
turtle.setheading(0)
turtle.pendown()
turtle.forward(100)
turtle.left(60)
turtle.forward(50)
turtle.left(120)
turtle.forward(100)
turtle.goto(-10, -90)
turtle.end_fill()

turtle.penup()
turtle.goto(-90, -140)
turtle.color("#1C88ED")
turtle.begin_fill()
turtle.setheading(60)
turtle.pendown()
for _ in range(2):
    turtle.forward(120)
    turtle.right(90)
    turtle.forward(40)
    turtle.right(90)
turtle.end_fill()

turtle.penup()
turtle.goto(-70, -200)
turtle.setheading(0)
turtle.color("black")
turtle.write("PERTAMINA", font=("Arial", 24, "bold"))

turtle.hideturtle()
turtle.done()
